### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by ccrawford93** [ExactTarget/fuel-java#11]
Most current project will not build. "mvn generate-sources" completes fine, however once running "mvn install -DskipTests" I receive the following error (verbosity excluded):

[ERROR] C:/.../ETSoapObject.java:[1287,29] name clash: getInternalProperty(<? extends ETSoapObject>, String) in ETSoapObject and getInternalProperty(<? extends ETObject>, String) in ETObject have the same erasure, yet neither hides the other.

The most recent checkout that I was able to build successfully was:

SHA-1: 14c7f226aa0ec0dec17921be545efe1f9fb64269

PS: On a side note, I'm attempting to update from .999999-pre1.0-1 in an attempt to fix issues with deleting a row into a data extension and deleting a data extension as I'm using deprecated services (at least in terms of the deleting the extension, the row deletion is not working at all). I figured the update could potentially remedy these situations, however I am unable to continue any further testing.

**Comment by imurdock** [comment]
This should be fixed--please verify you are able to build successfully. -ian
