### ISSUE TITLE
The code from the repo doesn't compile, packaging fails.

### ISSUE THREAD

**Issue by prem82** [ExactTarget/fuel-java#20]
I followed the instructions to compile the Fuel SDK from source. The packaging step fails with the compilation error. I didnt add/edit anything in the pom. It was straight from the git.

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/Workspace/FuelSDKTest/fuel-java/src/main/java/com/exacttarget/fuelsdk/audiencebuilder/ETAudience.java:[263,42] name clash: retrieve(com.exacttarget.fuelsdk.ETClient,java.lang.Class<com.exacttarget.fuelsdk.audiencebuilder.ETAudience>,java.lang.Integer,java.lang.Integer,com.exacttarget.fuelsdk.ETFilter) in com.exacttarget.fuelsdk.audiencebuilder.ETAudience and <T>retrieve(com.exacttarget.fuelsdk.ETClient,java.lang.Class<T>,java.lang.Integer,java.lang.Integer,com.exacttarget.fuelsdk.ETFilter) in com.exacttarget.fuelsdk.ETRestObject have the same erasure, yet neither hides the other
[ERROR] /D:/Workspace/FuelSDKTest/fuel-java/src/main/java/com/exacttarget/fuelsdk/audiencebuilder/ETDimension.java:[126,43] name clash: retrieve(com.exacttarget.fuelsdk.ETClient,java.lang.Class<com.exacttarget.fuelsdk.audiencebuilder.ETDimension>,java.lang.Integer,java.lang.Integer,com.exacttarget.fuelsdk.ETFilter) in com.exacttarget.fuelsdk.audiencebuilder.ETDimension and <T>retrieve(com.exacttarget.fuelsdk.ETClient,java.lang.Class<T>,java.lang.Integer,java.lang.Integer,com.exacttarget.fuelsdk.ETFilter) in com.exacttarget.fuelsdk.ETRestObject have the same erasure, yet neither hides the other

![image](https://cloud.githubusercontent.com/assets/5611865/7343026/cd1d66ac-ecd9-11e4-85b9-0de0cc885e57.png)

**Comment by snorith** [comment]
I'm also unable to build the .jar file because of the same error.

**Comment by imurdock** [comment]
This is fixed in the latest commit.
